import Head from 'next/head'
import '@/styles/globals.css'
import { SessionProvider } from "next-auth/react"
import { Toaster } from 'react-hot-toast';


export default function App({ Component, pageProps: { session, ...pageProps }, }) {
  return (
    <>
      <Head>
        <title>Postr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={session}>

        <Toaster />
        <Component {...pageProps} />
      </SessionProvider>
    </>
  )
}
